### ISSUE TITLE
Error: Cannot find module 'child_process_with_argv0'

### ISSUE THREAD

**Issue by dlee** [andrewffff/watch-make#1]
When I try running `watch-make`, I get this error:

```
❯ ./watch-make

module.js:340
    throw err;
          ^
Error: Cannot find module 'child_process_with_argv0'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dlee/code/watch-make/watch-make:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by eldilibra** [comment]
This is because this repo doesn't have a package.json that lists its dependencies, so when you installed it those weren't pulled down as well. @andrewffff mentions in the README that the next step for this project is to make an offical npm package, which includes adding that file. For now, just run `npm install child_process_with_argv0`. If you get similar errors, keep installing the listed module until you have all the dependencies. Hope that helps!
